-- =====================================================================
-- CrowdShip — Consolidated Final Schema
-- Generated by combining: 1783842934033_schema.sql (base) + 17 migrations
-- =====================================================================
--
-- NOTES ON THINGS WORTH REVIEWING (left intact below, flagged here):
--
-- 1. Duplicate/overlapping RLS policies on public.users:
--    The base schema created "Users can view their own profile" (SELECT,
--    own row only) and "Users can update their own profile" (UPDATE, own
--    row only). fix_users_rls.sql later ADDED "Allow view access for
--    authenticated users" (SELECT, any authenticated user, any row) and
--    "Allow update for own profile" (UPDATE, own row only). Because
--    Postgres RLS policies are OR'd together, the old SELECT policy is
--    now redundant (fully subsumed by the new permissive one), and the
--    two UPDATE policies are functionally identical. Both sets are kept
--    below to faithfully reflect the true post-migration database state,
--    but you likely want to DROP the two original ones.
--
-- 2. Double-payout risk on delivery:
--    complete_delivery() (from create_otp_verification_functions.sql)
--    directly updates shipments.status = 'delivered', credits the
--    business wallet with commission, and credits the traveler's
--    wallet_balance — all inline. Separately, the base schema's
--    trigger_shipment_delivered (calling handle_shipment_delivery())
--    fires AFTER UPDATE whenever a shipment's status transitions to
--    'delivered', and ALSO credits the traveler's wallet_balance and
--    clears escrow. Calling complete_delivery() will therefore fire
--    the trigger too, potentially paying the traveler twice and
--    double-counting the commission. Left as-is below; flagging for
--    your review.
--
-- 3. match_shipments_to_route had three revisions:
--      a) base schema.sql            — SQL function, lat/lng table output
--      b) add_route_matching.sql     — plpgsql, OR (pickup OR dropoff) match
--      c) fix_route_matching_function.sql — plpgsql, AND + direction check
--    (c) DROPs the exact signature created in (b) and is the final,
--    intended version, so only (c) is included below. (a) has a
--    different signature (radius_meters float, no default) and was
--    never dropped, so technically it still coexists as an overload in
--    a real migration history — included at the end of the functions
--    section for completeness, commented out. Uncomment only if you
--    actually want both overloads.
--
-- 4. shipments.pickup_location / dropoff_location are GEOGRAPHY(Point,4326)
--    while the newly-added shipments.pickup_route is GEOMETRY(LineString,
--    4326) — a type inconsistency inherited from add_route_matching.sql.
--
-- =====================================================================


-- =====================================================================
-- EXTENSIONS
-- =====================================================================
create extension if not exists postgis;
create extension if not exists "uuid-ossp";   -- for uuid_generate_v4()
create extension if not exists pgcrypto;      -- for gen_random_uuid()
create extension if not exists pg_cron;       -- for scheduled cleanup job


-- =====================================================================
-- CUSTOM TYPES
-- =====================================================================
create type kyc_status as enum ('pending', 'approved', 'rejected');
create type shipment_status as enum ('pending', 'accepted', 'in_transit', 'delivered', 'cancelled');
create type transaction_status as enum ('held', 'released', 'refunded');


-- =====================================================================
-- TABLE: public.users
-- =====================================================================
create table public.users (
  id uuid references auth.users not null primary key,
  full_name text,
  phone_number text,
  avatar_url text,
  is_kyc_verified boolean default false,
  trust_score int default 100,
  role text check (role in ('user', 'admin')) default 'user',
  wallet_balance decimal default 0.0,
  escrow_balance decimal default 0.0,
  created_at timestamptz default now(),
  -- added by add_is_suspended.sql
  is_suspended boolean default false,
  -- added by create_ratings_table.sql
  average_rating decimal(2,1) default 0.0,
  total_ratings integer default 0
);

alter table public.users enable row level security;

-- Original policies (base schema.sql)
create policy "Users can view their own profile" on public.users
  for select using (auth.uid() = id);

create policy "Users can insert their own profile" on public.users
  for insert with check (auth.uid() = id);

create policy "Users can update their own profile" on public.users
  for update using (auth.uid() = id);

-- Added by fix_users_rls.sql (see note #1 above re: overlap)
create policy "Allow view access for authenticated users"
on public.users for select
to authenticated
using (true);

create policy "Allow update for own profile"
on public.users for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);


-- =====================================================================
-- TABLE: public.kyc_documents
-- =====================================================================
create table public.kyc_documents (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) not null,
  document_url text not null,
  status kyc_status default 'pending',
  admin_note text,
  created_at timestamptz default now(),
  -- added by add_kyc_columns.sql
  document_type text,
  document_url_back text,
  proof_of_address_url text
);

comment on column public.kyc_documents.document_type is 'Type of ID document: passport, drivers_license, or national_id';

alter table public.kyc_documents enable row level security;

-- Final policy set from fix_kyc_rls.sql (superseded the base schema's
-- two original policies, which shared the same names and were dropped
-- and recreated identically here)
create policy "Users can view their own KYC docs"
on public.kyc_documents
for select
using (auth.uid() = user_id);

create policy "Users can upload KYC docs"
on public.kyc_documents
for insert
with check (auth.uid() = user_id);

create policy "Service role can access all KYC docs"
on public.kyc_documents
for select
using (
  auth.jwt() is null
  or
  auth.jwt()->>'role' = 'service_role'
);

create policy "Service role can update KYC docs"
on public.kyc_documents
for update
using (
  auth.jwt() is null
  or
  auth.jwt()->>'role' = 'service_role'
);


-- =====================================================================
-- TABLE: public.shipments
-- =====================================================================
create table public.shipments (
  id uuid default gen_random_uuid() primary key,
  sender_id uuid references public.users(id) not null,
  traveler_id uuid references public.users(id),
  title text not null,
  description text,
  weight_kg decimal,
  image_url text,
  pickup_address text,
  pickup_location geography(Point, 4326),
  dropoff_address text,
  dropoff_location geography(Point, 4326),
  status shipment_status default 'pending',
  offer_price decimal not null,
  pickup_otp text,
  delivery_otp text,
  created_at timestamptz default now(),
  -- added by add_cancellation_fields.sql
  cancelled_at timestamptz,
  cancelled_by uuid references public.users(id),
  cancellation_penalty decimal(10,2) default 0,
  -- added by add_delivered_at_column.sql
  delivered_at timestamptz,
  -- added by add_route_matching.sql
  pickup_route geometry(LineString, 4326),
  -- added by add_shipment_images.sql
  image_urls text[]
  -- bidding_enabled, accepted_bid_id, auto_accept_initial_price are
  -- added further below via ALTER TABLE, once public.bids exists
  -- (accepted_bid_id references bids.id)
);

alter table public.shipments enable row level security;

-- Policies from base schema.sql
create policy "Anyone can view pending shipments" on public.shipments
  for select using (status = 'pending');

create policy "Sender can view their shipments" on public.shipments
  for select using (auth.uid() = sender_id);

create policy "Traveler can view assigned shipments" on public.shipments
  for select using (auth.uid() = traveler_id);

create policy "Sender can create shipments" on public.shipments
  for insert with check (auth.uid() = sender_id);

create policy "Sender can update pending shipments" on public.shipments
  for update using (auth.uid() = sender_id and status = 'pending');

create policy "Traveler can update status" on public.shipments
  for update using (auth.uid() = traveler_id);

-- Added by fix_cancellation_rls.sql (see note #1 — overlaps the two
-- policies immediately above, kept for fidelity to the migration history)
create policy "Users can update own shipments" on public.shipments
for update
using (
    auth.uid() = sender_id or auth.uid() = traveler_id
)
with check (
    auth.uid() = sender_id or auth.uid() = traveler_id
);

-- Indexes
create index if not exists idx_shipments_cancelled_at on public.shipments(cancelled_at);
create index if not exists idx_shipments_cancelled_by on public.shipments(cancelled_by);
create index if not exists idx_shipments_delivered_at
  on public.shipments(delivered_at)
  where delivered_at is not null;
create index if not exists idx_shipments_pickup_route
  on public.shipments using gist(pickup_route);


-- =====================================================================
-- TABLE: public.trips  (base schema.sql, unmodified by migrations)
-- =====================================================================
create table public.trips (
  id uuid default gen_random_uuid() primary key,
  traveler_id uuid references public.users(id) not null,
  origin_address text,
  origin_location geography(Point, 4326),
  destination_address text,
  destination_location geography(Point, 4326),
  route_polyline text,
  departure_time timestamptz,
  created_at timestamptz default now()
);

alter table public.trips enable row level security;

create policy "Traveler can manage their trips" on public.trips
  for all using (auth.uid() = traveler_id);


-- =====================================================================
-- TABLE: public.transactions  (base schema.sql, unmodified by migrations)
-- =====================================================================
create table public.transactions (
  id uuid default gen_random_uuid() primary key,
  shipment_id uuid references public.shipments(id) not null,
  amount decimal not null,
  commission_fee decimal default 0.0,
  status transaction_status default 'held',
  created_at timestamptz default now()
);

alter table public.transactions enable row level security;

create policy "Users can view transactions concerning them" on public.transactions
  for select using (
    exists (
      select 1 from public.shipments s
      where s.id = shipment_id
      and (s.sender_id = auth.uid() or s.traveler_id = auth.uid())
    )
  );


-- =====================================================================
-- TABLE: public.bids  (create_bids_table.sql)
-- =====================================================================
create table if not exists public.bids (
    id uuid primary key default uuid_generate_v4(),
    shipment_id uuid not null references public.shipments(id) on delete cascade,
    traveler_id uuid not null references public.users(id) on delete cascade,
    offered_price decimal(10,2) not null check (offered_price > 0),
    status text not null check (status in ('pending', 'accepted', 'rejected', 'withdrawn')) default 'pending',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    -- Ensure one active bid per traveler per shipment
    unique(shipment_id, traveler_id)
);

create index if not exists idx_bids_shipment on public.bids(shipment_id);
create index if not exists idx_bids_traveler on public.bids(traveler_id);
create index if not exists idx_bids_status on public.bids(status);
create index if not exists idx_bids_created_at on public.bids(created_at desc);

-- Bidding-related columns on shipments (deferred here since they
-- reference public.bids.id)
alter table public.shipments
ADD COLUMN IF NOT EXISTS bidding_enabled boolean default false,
ADD COLUMN IF NOT EXISTS accepted_bid_id uuid references public.bids(id),
ADD COLUMN IF NOT EXISTS auto_accept_initial_price boolean default true;

alter table public.bids enable row level security;

create policy "Travelers can create bids"
on public.bids for insert
to authenticated
with check (
    auth.uid() = traveler_id and
    exists (
        select 1 from public.shipments
        where id = shipment_id
        and status = 'pending'
        and bidding_enabled = true
        and sender_id != auth.uid()
    )
);

create policy "Travelers can view own bids"
on public.bids for select
to authenticated
using (auth.uid() = traveler_id);

create policy "Senders can view shipment bids"
on public.bids for select
to authenticated
using (
    exists (
        select 1 from public.shipments
        where id = shipment_id
        and sender_id = auth.uid()
    )
);

create policy "Travelers can update own bids"
on public.bids for update
to authenticated
using (auth.uid() = traveler_id)
with check (auth.uid() = traveler_id);

create policy "Senders can update bid status"
on public.bids for update
to authenticated
using (
    exists (
        select 1 from public.shipments
        where id = shipment_id
        and sender_id = auth.uid()
    )
);


-- =====================================================================
-- TABLE: public.ratings  (create_ratings_table.sql)
-- =====================================================================
create table if not exists public.ratings (
  id uuid default gen_random_uuid() primary key,
  shipment_id uuid references public.shipments(id) on delete cascade not null unique,
  sender_id uuid references public.users(id) not null,
  traveler_id uuid references public.users(id) not null,
  rating integer check (rating >= 1 and rating <= 5) not null,
  comment text,
  created_at timestamptz default now()
);

alter table public.ratings enable row level security;

create policy "Senders can rate their delivered shipments" on public.ratings
  for insert
  with check (
    exists (
      select 1 from public.shipments
      where id = shipment_id
      and sender_id = auth.uid()
      and status = 'delivered'
    )
  );

create policy "Anyone can view ratings" on public.ratings
  for select
  using (true);

create index if not exists idx_ratings_traveler on public.ratings(traveler_id);
create index if not exists idx_ratings_shipment on public.ratings(shipment_id);


-- =====================================================================
-- TABLES: public.business_wallet / public.business_wallet_transactions
-- (create_business_wallet.sql)
-- =====================================================================
create table if not exists public.business_wallet (
    id uuid primary key default '00000000-0000-0000-0000-000000000001',
    balance decimal(10, 2) default 0,
    total_earned decimal(10, 2) default 0,
    total_withdrawn decimal(10, 2) default 0,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.business_wallet_transactions (
    id uuid primary key default uuid_generate_v4(),
    shipment_id uuid references public.shipments(id),
    amount decimal(10, 2) not null,
    type text check (type in ('commission', 'withdrawal')),
    description text,
    created_at timestamptz default now()
);

insert into public.business_wallet (id, balance, total_earned, total_withdrawn)
values ('00000000-0000-0000-0000-000000000001', 0, 0, 0)
on conflict (id) do nothing;

create index if not exists idx_business_wallet_transactions_shipment
on public.business_wallet_transactions(shipment_id);

create index if not exists idx_business_wallet_transactions_created
on public.business_wallet_transactions(created_at desc);


-- =====================================================================
-- STORAGE: avatars bucket  (create_storage_bucket.sql)
-- =====================================================================
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "Avatar images are publicly accessible" on storage.objects;
create policy "Avatar images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'avatars' );

drop policy if exists "Users can upload their own avatar" on storage.objects;
create policy "Users can upload their own avatar"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'avatars' and
    auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Authenticated users can upload avatars" on storage.objects;
create policy "Authenticated users can upload avatars"
  on storage.objects for insert
  to authenticated
  with check ( bucket_id = 'avatars' );

drop policy if exists "Users can update their own avatar" on storage.objects;
create policy "Users can update their own avatar"
  on storage.objects for update
  to authenticated
  using ( bucket_id = 'avatars' and owner = auth.uid() );

drop policy if exists "Users can delete their own avatar" on storage.objects;
create policy "Users can delete their own avatar"
  on storage.objects for delete
  to authenticated
  using ( bucket_id = 'avatars' and owner = auth.uid() );


-- =====================================================================
-- FUNCTIONS & TRIGGERS
-- =====================================================================

-- ---------------------------------------------------------------------
-- Route matching (final version, from fix_route_matching_function.sql)
-- ---------------------------------------------------------------------
create or replace function match_shipments_to_route(
    route_geometry text,
    radius_meters integer default 5000
)
returns setof public.shipments as $$
begin
    return query
    select s.*
    from public.shipments s
    where s.status = 'pending'
    and s.traveler_id is null
    and (
        st_dwithin(
            s.pickup_location::geography,
            st_geomfromtext(route_geometry, 4326)::geography,
            radius_meters::double precision
        )
        and
        st_dwithin(
            s.dropoff_location::geography,
            st_geomfromtext(route_geometry, 4326)::geography,
            radius_meters::double precision
        )
        and
        st_linelocatepoint(
            st_geomfromtext(route_geometry, 4326),
            s.pickup_location::geometry
        ) < st_linelocatepoint(
            st_geomfromtext(route_geometry, 4326),
            s.dropoff_location::geometry
        )
    )
    order by s.created_at desc;
end;
$$ language plpgsql stable security definer;

-- ---------------------------------------------------------------------
-- Escrow logic (base schema.sql, unmodified by migrations)
-- ---------------------------------------------------------------------
create or replace function handle_shipment_acceptance()
returns trigger
language plpgsql
security definer
as $$
begin
  if new.status = 'accepted' and old.status = 'pending' then
    update public.users
    set wallet_balance = wallet_balance - new.offer_price,
        escrow_balance = escrow_balance + new.offer_price
    where id = new.sender_id;

    insert into public.transactions (shipment_id, amount, status)
    values (new.id, new.offer_price, 'held');
  end if;
  return new;
end;
$$;

create trigger trigger_shipment_accepted
after update on public.shipments
for each row execute function handle_shipment_acceptance();

create or replace function handle_shipment_delivery()
returns trigger
language plpgsql
security definer
as $$
declare
  fee decimal;
  payout decimal;
begin
  if new.status = 'delivered' and old.status <> 'delivered' then
    fee := new.offer_price * 0.10;
    payout := new.offer_price - fee;

    update public.users
    set escrow_balance = escrow_balance - new.offer_price
    where id = new.sender_id;

    update public.users
    set wallet_balance = wallet_balance + payout
    where id = new.traveler_id;

    update public.transactions
    set status = 'released', commission_fee = fee
    where shipment_id = new.id;

  end if;
  return new;
end;
$$;

create trigger trigger_shipment_delivered
after update on public.shipments
for each row execute function handle_shipment_delivery();

-- ---------------------------------------------------------------------
-- New-user sync (final version, from add_user_trigger.sql)
-- ---------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, full_name, avatar_url, role)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url',
    'user'
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------
-- OTP verification (final versions, from create_otp_verification_functions.sql)
-- See note #2 above re: interaction with trigger_shipment_delivered
-- ---------------------------------------------------------------------
create or replace function complete_delivery(
    shipment_id uuid,
    otp_input text
)
returns boolean
language plpgsql
security definer
as $$
declare
    v_shipment record;
    v_base_amount decimal(10, 2);
    v_commission decimal(10, 2);
    v_traveler_amount decimal(10, 2);
begin
    select * into v_shipment from public.shipments where id = shipment_id;

    if v_shipment.delivery_otp = otp_input and v_shipment.status = 'in_transit' then
        v_commission := v_shipment.offer_price * 0.10;
        v_traveler_amount := v_shipment.offer_price - v_commission;

        update public.shipments
        set
            status = 'delivered',
            delivered_at = now()
        where id = shipment_id;

        update public.business_wallet
        set
            balance = balance + v_commission,
            total_earned = total_earned + v_commission,
            updated_at = now()
        where id = '00000000-0000-0000-0000-000000000001';

        insert into public.business_wallet_transactions (shipment_id, amount, type, description)
        values (shipment_id, v_commission, 'commission', 'Commission from shipment delivery');

        update public.users
        set wallet_balance = wallet_balance + v_traveler_amount
        where id = v_shipment.traveler_id;

        return true;
    else
        return false;
    end if;
end;
$$;

create or replace function complete_pickup(
    shipment_id uuid,
    otp_input text
)
returns boolean
language plpgsql
security definer
as $$
begin
    if exists (
        select 1 from public.shipments
        where id = shipment_id
        and pickup_otp = otp_input
        and status = 'accepted'
    ) then
        update public.shipments
        set status = 'in_transit'
        where id = shipment_id;

        return true;
    else
        return false;
    end if;
end;
$$;

-- ---------------------------------------------------------------------
-- Bids: auto-update updated_at (create_bids_table.sql)
-- ---------------------------------------------------------------------
create or replace function update_bids_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger bids_updated_at
before update on public.bids
for each row
execute function update_bids_updated_at();

-- ---------------------------------------------------------------------
-- Ratings: keep traveler stats in sync (create_ratings_table.sql)
-- ---------------------------------------------------------------------
create or replace function update_traveler_rating_stats()
returns trigger as $$
begin
  update public.users
  set
    average_rating = (select avg(rating) from public.ratings where traveler_id = new.traveler_id),
    total_ratings = (select count(*) from public.ratings where traveler_id = new.traveler_id)
  where id = new.traveler_id;

  return new;
end;
$$ language plpgsql security definer;

create trigger trigger_update_rating_stats
after insert on public.ratings
for each row
execute function update_traveler_rating_stats();

-- ---------------------------------------------------------------------
-- Email existence check (create_check_email_function.sql)
-- ---------------------------------------------------------------------
create or replace function public.check_email_exists(email_input text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
    return exists (
        select 1
        from auth.users
        where email = email_input
    );
end;
$$;

grant execute on function public.check_email_exists(text) to anon, authenticated;

-- ---------------------------------------------------------------------
-- Scheduled cleanup of unverified users (cleanup_unverified_users.sql)
-- ---------------------------------------------------------------------
create or replace function cleanup_unverified_users()
returns integer
language plpgsql
security definer
as $$
declare
    deleted_count integer;
begin
    with deleted as (
        delete from auth.users
        where created_at < now() - interval '20 minutes'
        and email_confirmed_at is null
        returning id
    )
    select count(*) into deleted_count from deleted;

    raise notice 'Cleaned up % unverified user(s)', deleted_count;

    return deleted_count;
end;
$$;

comment on function cleanup_unverified_users() is
'Deletes users who registered but never verified their email within 20 minutes. Returns count of deleted users.';

do $$
begin
    perform cron.unschedule('cleanup-unverified-users')
    where exists (select 1 from cron.job where jobname = 'cleanup-unverified-users');
exception
    when others then
        null;
end $$;

select cron.schedule(
    'cleanup-unverified-users',
    '*/5 * * * *',
    'SELECT cleanup_unverified_users();'
);


-- =====================================================================
-- DATA BACKFILL (from add_shipment_images.sql)
-- =====================================================================
update public.shipments
set image_urls = array[image_url]
where image_url is not null and image_urls is null;
-- Old image_url column intentionally retained (its drop was left
-- commented out in the original migration).


-- =====================================================================
-- End of consolidated schema
-- =====================================================================
